require 'lims-bridge-app/plate_creator/message_handlers/order_handler'
require 'lims-bridge-app/plate_creator/message_handlers/plate_handler'
require 'lims-bridge-app/plate_creator/message_handlers/tuberackmove_handler'
require 'lims-bridge-app/plate_creator/message_handlers/update_aliquots_handler'
require 'lims-bridge-app/plate_creator/message_handlers/labellable_handler'
